#!/bin/tcsh


switch ($1)

	case cxi25410:
	rsync -av --exclude '.DS_Store' --exclude 'psexport' --exclude '.git*' --exclude '*~' . sellberg@psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi25410/res/iceFinderCampaign/
	breaksw
	
	case cxi74613:
	rsync -av --exclude '.DS_Store' --exclude 'psexport' --exclude '.git*' --exclude '*~' . sellberg@psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi74613/res/iceFinderCampaign/
	breaksw
	
	case sellberg:
	rsync -av --exclude '.DS_Store' --exclude '.git*' --exclude '*~' . sellberg@psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi25410/scratch/sellberg/iceFinder/
	breaksw
	
	case averageRuns-:
	scp averageRuns-*.py sellberg@psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi25410/res/iceFinderCampaign/
	
endsw
